# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0702dc500af947c47c468e7ce5fd83b4242b55c4b093c6eb0e694819388501363cc058fc62cd9aa6b7df7e1b623a0637728431c8458a6700ca4d8692c59017f

test:
  secret_key_base: 98c44eb3bcf3ad6479cd0c850899ec4ba8e9e31ec189dce83976f26e938f9e80c514c81d60911ffcb33cde566c05c1e3139ec35683ff318d33b36ef5d5759c53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
